### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by MaddoScientisto** [NotWoods/unity-polygon-2d-editor#1]
This is a nice and useful script but the chosen license (GPL v3) really prevents usage of the code in anything that is not open source, even with attribution. 

Could it be possible to relicense the code under another license, like MIT or anything else? https://choosealicense.com/ for a list of more permissive licenses.

Of course that's assuming you didn't specifically want the license to be GPL v3, if that's the case I can understand your choice.

**Comment by NotWoods** [comment]
Sure thing, I'll change the license to MIT when I'm home later today.

**Comment by MaddoScientisto** [comment]
Thank you! Now I can use this with a clean conscience!
